version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    depends_on: 
      - mongodb
    build: 
      dockerfile: Dockerfile
      context: ./MongoDB
    links:
      - mongodb
    restart: on-failure

  web:
    depends_on:
      - mongodb
      - mongo-seed
    build:
      dockerfile: Dockerfile
      context: ./Biopredict
    ports:
      - "5050:5050"


  
